# Generated by Django 4.2.1 on 2023-05-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='oid',
        ),
    ]
